apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - spring-boot/
  # - fastapi/  # BE 파이프라인 검증 후 활성화
  - ingress-api.yaml
  - ingress-ws.yaml
  - networkpolicy.yaml

labels:
  - pairs:
      managed-by: argocd
      project: tasteam
