apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: spring-boot-runtime
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-parameter-store
    kind: ClusterSecretStore
  target:
    name: spring-boot-runtime
    creationPolicy: Owner
  dataFrom:
    - find:
        path: /prod/tasteam/backend
        name:
          regexp: ".*"
      rewrite:
        - regexp:
            source: "/prod/tasteam/backend/(.*)"
            target: "$1"
