apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: fastapi-runtime
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-ssm
    kind: ClusterSecretStore
  target:
    name: fastapi-runtime
    creationPolicy: Owner
  dataFrom:
    - find:
        path: /prod/tasteam/fastapi
        name:
          regexp: ".*"
      rewrite:
        - regexp:
            source: "/prod/tasteam/fastapi/(.*)"
            target: "$1"
