apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: app-prod

resources:
  - ../../base
  - external-secret.yaml
  - external-secret-fastapi.yaml

patches:
  # Spring Boot — prod 이미지 태그 (CI가 이 파일의 newTag를 업데이트)
  - target:
      kind: Deployment
      name: spring-boot
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 2

  # FastAPI — prod replicas
  - target:
      kind: Deployment
      name: fastapi
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 1

  # Ingress host — prod 도메인
  - target:
      kind: Ingress
      name: tasteam-api-ingress
    patch: |-
      - op: replace
        path: /spec/rules/0/host
        value: api.tasteam.kr

  - target:
      kind: Ingress
      name: tasteam-ws-ingress
    patch: |-
      - op: replace
        path: /spec/rules/0/host
        value: api.tasteam.kr

images:
  - name: SPRING_BOOT_IMAGE
    newName: 203802643061.dkr.ecr.ap-northeast-2.amazonaws.com/tasteam-be
    newTag: 11cff48
  - name: FASTAPI_IMAGE
    newName: 203802643061.dkr.ecr.ap-northeast-2.amazonaws.com/tasteam-ai
    newTag: 712e2d4

configMapGenerator:
  - name: spring-config
    behavior: replace
    literals:
      - profile=prod
  - name: fastapi-config
    behavior: replace
    literals:
      - env=prod
