global:
  scrape_interval: 30s  # 메모리 절약을 위해 30초로 설정
  evaluation_interval: 30s

scrape_configs:
  - job_name: 'spring'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets:
          - 'host.docker.internal:18080'
          - 'host.docker.internal:18081'
        labels:
          environment: stg
          service: tasteam-api
          role: api

  - job_name: 'redis'
    static_configs:
      - targets:
          - 'redis-exporter:9121'
        labels:
          environment: stg
          namespace: stg
          service: tasteam-redis
          role: cache

  - job_name: 'postgres'
    static_configs:
      - targets:
          - 'postgres-exporter:9187'
        labels:
          environment: stg
          service: tasteam-db
          role: database
