-- Auto-generated dummy seed SQL for Tasteam
-- generated_at: 2026-03-08 05:14:51 UTC
-- run_token: 546d8cf5709d
-- This script is generated by loadtest/seed/generate_dummy_seed_sql.py

BEGIN;
SET LOCAL client_min_messages TO WARNING;

CREATE TEMP TABLE tmp_dummy_member (seq INTEGER PRIMARY KEY, id BIGINT NOT NULL) ON COMMIT DROP;
CREATE TEMP TABLE tmp_dummy_restaurant (seq INTEGER PRIMARY KEY, id BIGINT NOT NULL) ON COMMIT DROP;
CREATE TEMP TABLE tmp_dummy_group (seq INTEGER PRIMARY KEY, id BIGINT NOT NULL) ON COMMIT DROP;
CREATE TEMP TABLE tmp_dummy_subgroup (seq INTEGER PRIMARY KEY, id BIGINT NOT NULL, group_id BIGINT NOT NULL, group_seq INTEGER NOT NULL, subgroup_index INTEGER NOT NULL) ON COMMIT DROP;
CREATE TEMP TABLE tmp_dummy_chat_room (seq INTEGER PRIMARY KEY, id BIGINT NOT NULL, subgroup_id BIGINT NOT NULL, group_seq INTEGER NOT NULL, subgroup_index INTEGER NOT NULL) ON COMMIT DROP;
CREATE TEMP TABLE tmp_dummy_menu_category (seq INTEGER PRIMARY KEY, id BIGINT NOT NULL, restaurant_id BIGINT NOT NULL, display_order INTEGER NOT NULL) ON COMMIT DROP;
CREATE TEMP TABLE tmp_dummy_review (seq INTEGER PRIMARY KEY, id BIGINT NOT NULL, member_id BIGINT NOT NULL, restaurant_id BIGINT NOT NULL, group_id BIGINT NOT NULL, subgroup_id BIGINT, is_recommended BOOLEAN NOT NULL) ON COMMIT DROP;
CREATE TEMP TABLE tmp_dummy_keyword (seq INTEGER PRIMARY KEY, id BIGINT NOT NULL) ON COMMIT DROP;
CREATE TEMP TABLE tmp_dummy_food_category (seq INTEGER PRIMARY KEY, id BIGINT NOT NULL) ON COMMIT DROP;

-- Reference dictionaries bootstrap for fresh DB
INSERT INTO food_category (name)
SELECT fc.name
FROM UNNEST(ARRAY['한식', '중식', '일식', '양식', '카페', '치킨', '피자']::TEXT[]) AS fc(name)
WHERE NOT EXISTS (SELECT 1 FROM food_category);

WITH seed_keyword(type, name) AS (
  VALUES
    ('VISIT_PURPOSE', '점심'),
    ('VISIT_PURPOSE', '저녁'),
    ('VISIT_PURPOSE', '회식'),
    ('VISIT_PURPOSE', '데이트'),
    ('COMPANION_TYPE', '혼밥'),
    ('COMPANION_TYPE', '친구'),
    ('COMPANION_TYPE', '연인'),
    ('COMPANION_TYPE', '동료'),
    ('WAITING_EXPERIENCE', '바로 입장'),
    ('WAITING_EXPERIENCE', '대기 짧음'),
    ('WAITING_EXPERIENCE', '대기 있음'),
    ('POSITIVE_ASPECT', '맛있음'),
    ('POSITIVE_ASPECT', '친절함'),
    ('POSITIVE_ASPECT', '가성비 좋음'),
    ('POSITIVE_ASPECT', '분위기 좋음')
)
INSERT INTO keyword (type, name)
SELECT sk.type, sk.name
FROM seed_keyword sk
WHERE NOT EXISTS (SELECT 1 FROM keyword);

INSERT INTO tmp_dummy_keyword (seq, id)
SELECT ROW_NUMBER() OVER (ORDER BY id), id
FROM keyword
ORDER BY id;

INSERT INTO tmp_dummy_food_category (seq, id)
SELECT ROW_NUMBER() OVER (ORDER BY id), id
FROM food_category
ORDER BY id;

-- Members
INSERT INTO tmp_dummy_member (seq, id)
SELECT gs, nextval('member_seq')
FROM generate_series(1, 10000) AS gs;

WITH cfg AS (
  SELECT ARRAY['min', 'ji', 'seo', 'ha', 'do', 'yeon', 'jun', 'tae', 'su', 'hyeon']::TEXT[] AS email_a,
         ARRAY['kim', 'lee', 'park', 'choi', 'jung', 'han', 'yoon', 'oh', 'lim', 'kang']::TEXT[] AS email_b,
         ARRAY['gmail.com', 'naver.com', 'kakao.com', 'outlook.com', 'tasteam.kr']::TEXT[] AS email_domains,
         ARRAY['맛집헌터', '퇴근러', '점심탐험가', '야식러버', '국밥수집가', '카페순례자']::TEXT[] AS nick_adj,
         ARRAY['민초', '새우', '곱창', '파스타', '초밥', '버거', '마라', '치킨']::TEXT[] AS nick_noun,
         ARRAY['근처 직장인이라 점심 맛집 자주 찾아요.', '주말에는 동네 카페 투어를 즐깁니다.', '새로운 메뉴 도전하는 걸 좋아해요.', '웨이팅 짧고 회전 빠른 집 선호합니다.', '혼밥 가능한 조용한 공간을 찾고 있어요.']::TEXT[] AS intro_lines
)
INSERT INTO member (id, email, nickname, status, role, profile_image_url, introduction, last_login_at, agreed_terms_at, agreed_privacy_at, created_at, updated_at)
SELECT
  m.id,
  LOWER('dummy' || '-' || '546d8cf5709d' || '-' || m.seq || '+' || cfg.email_a[((m.seq - 1) % CARDINALITY(cfg.email_a)) + 1] || '.' || cfg.email_b[((m.seq - 1) % CARDINALITY(cfg.email_b)) + 1] || '@' || cfg.email_domains[((m.seq - 1) % CARDINALITY(cfg.email_domains)) + 1]),
  CASE    WHEN MOD(m.seq, 3) = 0 THEN '더미유저' || '-' || LPAD(m.seq::TEXT, 4, '0')     WHEN MOD(m.seq, 3) = 1 THEN cfg.nick_adj[((m.seq - 1) % CARDINALITY(cfg.nick_adj)) + 1] || cfg.nick_noun[((m.seq - 1) % CARDINALITY(cfg.nick_noun)) + 1] || m.seq     ELSE cfg.nick_noun[((m.seq - 1) % CARDINALITY(cfg.nick_noun)) + 1] || '-' || cfg.nick_adj[((m.seq - 1) % CARDINALITY(cfg.nick_adj)) + 1] || '-' || (m.seq % 100)   END,
  'ACTIVE',
  'USER',
  CASE WHEN MOD(m.seq, 4) = 0 THEN NULL ELSE 'https://cdn.tasteam.kr/profiles' || '/' || '546d8cf5709d' || '/' || m.id || '.webp' END,
  CASE     WHEN MOD(m.seq, 6) = 0 THEN NULL     WHEN MOD(m.seq, 2) = 0 THEN cfg.intro_lines[((m.seq - 1) % CARDINALITY(cfg.intro_lines)) + 1]     ELSE cfg.intro_lines[((m.seq - 1) % CARDINALITY(cfg.intro_lines)) + 1] || ' ' || cfg.intro_lines[((m.seq) % CARDINALITY(cfg.intro_lines)) + 1]   END,
  NOW() - ((m.seq % 90) || ' days')::INTERVAL - ((m.seq % 24) || ' hours')::INTERVAL,
  NOW() - ((m.seq % 180) || ' days')::INTERVAL,
  NOW() - ((m.seq % 180) || ' days')::INTERVAL + INTERVAL '10 minutes',
  NOW() - ((m.seq % 365) || ' days')::INTERVAL,
  NOW() - ((m.seq % 365) || ' days')::INTERVAL
FROM tmp_dummy_member m
CROSS JOIN cfg
ORDER BY m.seq;

-- Member notification preferences
WITH cfg AS (
  SELECT ARRAY['WEB', 'PUSH', 'EMAIL', 'SMS']::TEXT[] AS channels,
         ARRAY['CHAT', 'SYSTEM', 'NOTICE']::TEXT[] AS notif_types
)
INSERT INTO member_notification_preference (member_id, channel, notification_type, is_enabled, created_at, updated_at)
SELECT
  m.id,
  ch.channel,
  nt.notif_type,
  ((((m.seq - 1) * 12) + ((ch.channel_ord - 1) * 3) + nt.type_ord) % 5) <> 0,
  NOW(),
  NOW()
FROM tmp_dummy_member m
CROSS JOIN cfg
CROSS JOIN UNNEST(cfg.channels) WITH ORDINALITY AS ch(channel, channel_ord)
CROSS JOIN UNNEST(cfg.notif_types) WITH ORDINALITY AS nt(notif_type, type_ord)
ON CONFLICT DO NOTHING;

-- Member search histories
WITH cfg AS (
  SELECT ARRAY['한식', '중식', '일식', '양식', '분식', '카페', '치킨', '피자', '버거', '초밥', '삼겹살', '냉면', '국밥', '라멘', '파스타']::TEXT[] AS keywords
)
INSERT INTO member_search_history (member_id, keyword, count, created_at, updated_at)
SELECT
  m.id,
  cfg.keywords[(((m.seq - 1) + kw.off) % CARDINALITY(cfg.keywords)) + 1],
  1,
  NOW(),
  NOW()
FROM tmp_dummy_member m
CROSS JOIN cfg
JOIN generate_series(0, 3) AS kw(off)
  ON kw.off < (2 + ((m.seq - 1) % 4))
ON CONFLICT DO NOTHING;

-- Restaurants
INSERT INTO tmp_dummy_restaurant (seq, id)
SELECT gs, nextval(pg_get_serial_sequence('restaurant', 'id'))
FROM generate_series(1, 10000) AS gs;

WITH cfg AS (
  SELECT ARRAY['강남', '연남', '성수', '잠실', '광화문', '해운대', '판교', '홍대']::TEXT[] AS left_tokens,
         ARRAY['화로집', '스시바', '국밥집', '브런치랩', '포차', '카페', '버거하우스', '파스타키친']::TEXT[] AS right_tokens,
         ARRAY['서울시', '서울시', '서울시', '서울시', '서울시', '서울시', '서울시', '경기도', '경기도', '경기도', '부산시', '인천시', '대구시']::TEXT[] AS sidos,
         ARRAY['강남구', '서초구', '마포구', '송파구', '강서구', '종로구', '중구', '분당구', '수원시', '일산동구', '해운대구', '연수구', '수성구']::TEXT[] AS sigungus
)
INSERT INTO restaurant (id, name, full_address, location, phone_number, vector_epoch, created_at, updated_at)
SELECT
  r.id,
  '더미식당' || '-' || '546d8cf5709d' || '-' || cfg.left_tokens[((r.seq - 1) % CARDINALITY(cfg.left_tokens)) + 1] || ' ' || cfg.right_tokens[((r.seq - 1) % CARDINALITY(cfg.right_tokens)) + 1] || ' ' || (MOD(r.seq, 20) + 1) || '호',
  cfg.sidos[((r.seq - 1) % CARDINALITY(cfg.sidos)) + 1] || ' ' || cfg.sigungus[((r.seq - 1) % CARDINALITY(cfg.sigungus)) + 1] || ' ' || '역삼동' || ' ' || (MOD(r.seq, 300) + 1) || '-' || (MOD(r.seq * 7, 50) + 1),
  ST_SetSRID(ST_MakePoint(126.0 + MOD((r.seq * 37)::BIGINT, 3600) / 1000.0, 33.1 + MOD((r.seq * 53)::BIGINT, 5500) / 1000.0), 4326),
  '0' || (2 + MOD(r.seq, 8)) || '-' || LPAD((1000 + MOD(r.seq * 31, 9000))::TEXT, 4, '0') || '-' || LPAD((1000 + MOD(r.seq * 17, 9000))::TEXT, 4, '0'),
  0,
  NOW() - ((r.seq % 365) || ' days')::INTERVAL,
  NOW() - ((r.seq % 365) || ' days')::INTERVAL
FROM tmp_dummy_restaurant r
CROSS JOIN cfg
ORDER BY r.seq;

-- Restaurant address (1:1)
WITH cfg AS (
  SELECT ARRAY['서울시', '서울시', '서울시', '서울시', '서울시', '서울시', '서울시', '경기도', '경기도', '경기도', '부산시', '인천시', '대구시']::TEXT[] AS sidos, ARRAY['강남구', '서초구', '마포구', '송파구', '강서구', '종로구', '중구', '분당구', '수원시', '일산동구', '해운대구', '연수구', '수성구']::TEXT[] AS sigungus
)
INSERT INTO restaurant_address (restaurant_id, sido, sigungu, eupmyeondong, postal_code, created_at, updated_at)
SELECT
  r.id,
  cfg.sidos[((r.seq - 1) % CARDINALITY(cfg.sidos)) + 1],
  cfg.sigungus[((r.seq - 1) % CARDINALITY(cfg.sigungus)) + 1],
  '역삼동',
  '06000',
  NOW(),
  NOW()
FROM tmp_dummy_restaurant r
CROSS JOIN cfg
ORDER BY r.seq;

-- Restaurant weekly schedule (7 rows per restaurant)
INSERT INTO restaurant_weekly_schedule (restaurant_id, day_of_week, open_time, close_time, is_closed, effective_from, effective_to, created_at, updated_at)
SELECT
  r.id,
  d.day_of_week,
  CASE WHEN d.day_of_week = 7 THEN NULL ELSE TIME '09:00:00' END,
  CASE WHEN d.day_of_week = 7 THEN NULL ELSE TIME '21:00:00' END,
  (d.day_of_week = 7),
  NULL,
  NULL,
  NOW(),
  NOW()
FROM tmp_dummy_restaurant r
CROSS JOIN generate_series(1, 7) AS d(day_of_week)
ORDER BY r.seq, d.day_of_week;

-- Restaurant food categories (food_category가 비어있으면 skip)
DO $$
DECLARE
  category_count INTEGER;
BEGIN
  SELECT COUNT(*) INTO category_count FROM tmp_dummy_food_category;
  IF category_count > 0 THEN
    INSERT INTO restaurant_food_category (restaurant_id, food_category_id)
    SELECT
      r.id,
      fc.id
    FROM tmp_dummy_restaurant r
    JOIN generate_series(0, 1) AS c(off)
      ON c.off < (1 + ((r.seq - 1) % 2))
    JOIN tmp_dummy_food_category fc
      ON fc.seq = ((((r.seq - 1) + c.off) % category_count) + 1)
    ON CONFLICT DO NOTHING;
  END IF;
END $$;

-- Menu categories
INSERT INTO tmp_dummy_menu_category (seq, id, restaurant_id, display_order)
SELECT
  ROW_NUMBER() OVER (ORDER BY r.seq, c.idx),
  nextval(pg_get_serial_sequence('menu_category', 'id')),
  r.id,
  c.idx - 1
FROM tmp_dummy_restaurant r
CROSS JOIN generate_series(1, 2) AS c(idx)
ORDER BY r.seq, c.idx;

WITH cfg AS (
  SELECT ARRAY['메인', '음료']::TEXT[] AS category_names
)
INSERT INTO menu_category (id, restaurant_id, name, display_order, created_at, updated_at)
SELECT
  mc.id,
  mc.restaurant_id,
  cfg.category_names[mc.display_order + 1],
  mc.display_order,
  NOW(),
  NOW()
FROM tmp_dummy_menu_category mc
CROSS JOIN cfg
ORDER BY mc.seq;

-- Menus
WITH cfg AS (
  SELECT ARRAY['화로집', '스시바', '국밥집', '브런치랩', '포차', '카페', '버거하우스', '파스타키친']::TEXT[] AS menu_tokens
)
INSERT INTO menu (category_id, name, description, price, image_url, is_recommended, display_order, created_at, updated_at)
SELECT
  mc.id,
  '더미메뉴' || '-' || cfg.menu_tokens[((mc.seq - 1) % CARDINALITY(cfg.menu_tokens)) + 1] || '-' || (((mc.seq - 1) * 3) + m.menu_idx),
  CASE     WHEN MOD(((mc.seq - 1) * 3) + m.menu_idx, 3) = 0 THEN '대표 메뉴입니다.'     ELSE '재료 본연의 풍미를 살린 메뉴입니다. 추천 조합으로 함께 즐겨보세요.'   END,
  (MOD(((mc.seq - 1) * 3) + (m.menu_idx - 1), 5) * 1000) + 8000,
  CASE WHEN MOD(((mc.seq - 1) * 3) + m.menu_idx, 4) = 0 THEN NULL ELSE 'https://cdn.tasteam.kr/menus' || '/' || '546d8cf5709d' || '/' || (((mc.seq - 1) * 3) + m.menu_idx) || '.jpg' END,
  (MOD(((mc.seq - 1) * 3) + (m.menu_idx - 1), 3) = 0),
  m.menu_idx - 1,
  NOW(),
  NOW()
FROM tmp_dummy_menu_category mc
CROSS JOIN cfg
CROSS JOIN generate_series(1, 3) AS m(menu_idx)
ORDER BY mc.seq, m.menu_idx;

-- Groups
INSERT INTO tmp_dummy_group (seq, id)
SELECT gs, nextval('group_seq')
FROM generate_series(1, 1500) AS gs;

INSERT INTO "group" (id, name, type, logo_image_url, address, detail_address, location, join_type, email_domain, status, created_at, updated_at)
WITH cfg AS (
  SELECT ARRAY['백엔드', '프론트엔드', '데이터', 'AI', '디자인', 'PM', '운영', '인프라']::TEXT[] AS topics,
         ARRAY['서울시', '서울시', '서울시', '서울시', '서울시', '서울시', '서울시', '경기도', '경기도', '경기도', '부산시', '인천시', '대구시']::TEXT[] AS sidos,
         ARRAY['강남구', '서초구', '마포구', '송파구', '강서구', '종로구', '중구', '분당구', '수원시', '일산동구', '해운대구', '연수구', '수성구']::TEXT[] AS sigungus
)
SELECT
  g.id,
  '더미그룹' || '-' || '546d8cf5709d' || '-' || cfg.topics[((g.seq - 1) % CARDINALITY(cfg.topics)) + 1] || '-' || g.seq,
  CASE WHEN MOD(g.seq, 5) = 0 THEN 'OFFICIAL' ELSE 'UNOFFICIAL' END,
  CASE WHEN MOD(g.seq, 3) = 0 THEN NULL ELSE 'https://cdn.tasteam.kr/groups' || '/' || '546d8cf5709d' || '/' || g.id || '.png' END,
  cfg.sidos[((g.seq - 1) % CARDINALITY(cfg.sidos)) + 1] || ' ' || cfg.sigungus[((g.seq - 1) % CARDINALITY(cfg.sigungus)) + 1] || ' ' || '서울시 강남구 테스트로' || ' ' || g.seq,
  '빌딩 ' || (MOD(g.seq, 40) + 1) || '층',
  ST_SetSRID(ST_MakePoint(126.0 + MOD((g.seq * 41)::BIGINT, 3600) / 1000.0, 33.1 + MOD((g.seq * 59)::BIGINT, 5500) / 1000.0), 4326),
  CASE WHEN MOD(g.seq, 4) = 0 THEN 'EMAIL' ELSE 'PASSWORD' END,
  CASE WHEN MOD(g.seq, 4) = 0 THEN 'team' || g.seq || '.tasteam.dev' ELSE NULL END,
  'ACTIVE',
  NOW() - ((g.seq % 365) || ' days')::INTERVAL,
  NOW() - ((g.seq % 365) || ' days')::INTERVAL
FROM tmp_dummy_group g
CROSS JOIN cfg
ORDER BY g.seq;

-- Subgroups
INSERT INTO tmp_dummy_subgroup (seq, id, group_id, group_seq, subgroup_index)
SELECT
  ROW_NUMBER() OVER (ORDER BY g.seq, sg.subgroup_idx),
  nextval('subgroup_seq'),
  g.id,
  g.seq,
  sg.subgroup_idx
FROM tmp_dummy_group g
CROSS JOIN generate_series(1, 4) AS sg(subgroup_idx)
ORDER BY g.seq, sg.subgroup_idx;

INSERT INTO subgroup (id, group_id, name, description, profile_image_url, join_type, join_password, status, member_count, created_at, updated_at)
WITH cfg AS (
  SELECT ARRAY['점심', '야식', '회식', '카페', '러닝', '스터디', '프로젝트', '탐방']::TEXT[] AS topics
)
SELECT
  sg.id,
  sg.group_id,
  '더미팀' || '-' || cfg.topics[((sg.seq - 1) % CARDINALITY(cfg.topics)) + 1] || '-' || sg.group_seq || '-' || sg.subgroup_index,
  '관심사 기반 소규모 모임입니다. 일정 조율 후 함께 방문해요.',
  CASE WHEN MOD(sg.seq, 3) = 0 THEN NULL ELSE 'https://cdn.tasteam.kr/subgroups' || '/' || '546d8cf5709d' || '/' || sg.id || '.jpg' END,
  CASE WHEN MOD(sg.seq, 5) = 0 THEN 'PASSWORD' ELSE 'OPEN' END,
  CASE WHEN MOD(sg.seq, 5) = 0 THEN 'sg-pass' || '-' || sg.group_seq || '-' || sg.subgroup_index ELSE NULL END,
  'ACTIVE',
  0,
  NOW() - ((sg.seq % 300) || ' days')::INTERVAL,
  NOW() - ((sg.seq % 300) || ' days')::INTERVAL
FROM tmp_dummy_subgroup sg
CROSS JOIN cfg
ORDER BY sg.seq;

-- Chat rooms (subgroup 1:1)
INSERT INTO tmp_dummy_chat_room (seq, id, subgroup_id, group_seq, subgroup_index)
SELECT
  sg.seq,
  nextval('chat_room_id_seq'),
  sg.id,
  sg.group_seq,
  sg.subgroup_index
FROM tmp_dummy_subgroup sg
ORDER BY sg.seq;

INSERT INTO chat_room (id, subgroup_id, created_at)
SELECT id, subgroup_id, NOW()
FROM tmp_dummy_chat_room
ORDER BY seq;

-- 명시적 id 삽입으로 인해 identity 시퀀스가 뒤처지는 문제 방지
SELECT setval(pg_get_serial_sequence('chat_room', 'id'), COALESCE((SELECT MAX(id) FROM chat_room), 0), true);

-- Group members
INSERT INTO group_member (id, group_id, member_id, created_at)
SELECT
  nextval('group_member_seq'),
  g.id,
  m.id,
  NOW()
FROM tmp_dummy_group g
JOIN generate_series(0, 29) AS off(member_offset) ON TRUE
JOIN tmp_dummy_member m
  ON m.seq = (((((g.seq * 37) % 10000) + off.member_offset) % 10000) + 1)
ON CONFLICT DO NOTHING;

-- Subgroup members
INSERT INTO subgroup_member (id, subgroup_id, member_id, created_at)
SELECT
  nextval('subgroup_member_seq'),
  sg.id,
  m.id,
  NOW()
FROM tmp_dummy_subgroup sg
JOIN generate_series(0, 29) AS off(member_offset) ON TRUE
JOIN tmp_dummy_member m
  ON m.seq = ((((sg.group_seq * 37) % 10000) + ((((sg.group_seq * 31 + sg.subgroup_index * 17) % 30) + off.member_offset) % 30)) % 10000) + 1
ON CONFLICT DO NOTHING;

-- Chat room members
INSERT INTO chat_room_member (member_id, chat_room_id, created_at, updated_at)
SELECT
  m.id,
  cr.id,
  NOW(),
  NOW()
FROM tmp_dummy_chat_room cr
JOIN tmp_dummy_subgroup sg ON sg.id = cr.subgroup_id
JOIN generate_series(0, 29) AS off(member_offset) ON TRUE
JOIN tmp_dummy_member m
  ON m.seq = ((((sg.group_seq * 37) % 10000) + ((((sg.group_seq * 31 + sg.subgroup_index * 17) % 30) + off.member_offset) % 30)) % 10000) + 1
ON CONFLICT DO NOTHING;

UPDATE subgroup
SET member_count = 30
WHERE id IN (SELECT id FROM tmp_dummy_subgroup);

-- Chat messages
WITH cfg AS (
  SELECT ARRAY['좋아요', '여기 어때요?', '지금 출발합니다', '메뉴 추천 부탁해요', '오늘 사람 많네요']::TEXT[] AS short_msgs,
         ARRAY['가게 분위기가 깔끔하고 대화하기 편했어요.', '점심 피크에는 웨이팅이 있으니 11시 반 전에 가는 걸 추천해요.', '가격대는 조금 있지만 양이 충분해서 만족도가 높았어요.', '재방문 의사 있고, 다음에는 다른 메뉴도 시도해보려 해요.']::TEXT[] AS long_msgs
)
INSERT INTO chat_message (chat_room_id, member_id, type, content, created_at)
SELECT
  cr.id,
  m.id,
  'TEXT',
  CASE     WHEN MOD(msg.message_idx, 5) IN (0, 1) THEN '더미 채팅 메시지' || ' #' || (((cr.seq - 1) * 167) + msg.message_idx) || ' ' || cfg.short_msgs[((msg.message_idx - 1) % CARDINALITY(cfg.short_msgs)) + 1]     ELSE '더미 채팅 메시지' || ' #' || (((cr.seq - 1) * 167) + msg.message_idx) || ' ' || cfg.long_msgs[((msg.message_idx - 1) % CARDINALITY(cfg.long_msgs)) + 1]   END,
  NOW() - ((cr.seq % 90) || ' days')::INTERVAL
FROM tmp_dummy_chat_room cr
CROSS JOIN cfg
JOIN tmp_dummy_subgroup sg ON sg.id = cr.subgroup_id
JOIN generate_series(1, 167) AS msg(message_idx) ON TRUE
JOIN tmp_dummy_member m
  ON m.seq = ((((sg.group_seq * 37) % 10000) + ((((sg.group_seq * 31 + sg.subgroup_index * 17) % 30) + ((msg.message_idx - 1) % 30)) % 30)) % 10000) + 1
ORDER BY cr.seq, msg.message_idx;

-- Update last_read_message_id for 70% of chat_room_member rows
UPDATE chat_room_member crm
SET last_read_message_id = latest.max_id
FROM (
  SELECT chat_room_id, MAX(id) AS max_id
  FROM chat_message
  WHERE chat_room_id IN (SELECT id FROM tmp_dummy_chat_room)
  GROUP BY chat_room_id
) AS latest
WHERE crm.chat_room_id = latest.chat_room_id
  AND (crm.id % 10) < 7;

-- Reviews
INSERT INTO tmp_dummy_review (seq, id, member_id, restaurant_id, group_id, subgroup_id, is_recommended)
SELECT
  rv.seq,
  nextval(pg_get_serial_sequence('review', 'id')),
  m.id,
  rest.id,
  g.id,
  sg.id,
  (MOD(rv.seq - 1, 4) != 0)
FROM generate_series(1, 300000) AS rv(seq)
JOIN tmp_dummy_member m
  ON m.seq = (CASE WHEN MOD(rv.seq - 1, 10) < 8 THEN ((rv.seq - 1) % 2000) + 1 ELSE 2000 + (((rv.seq - 1) % 8000) + 1) END)
JOIN tmp_dummy_group g
  ON g.seq = (((rv.seq - 1) % 1500) + 1)
LEFT JOIN tmp_dummy_subgroup sg
  ON sg.group_id = g.id AND sg.subgroup_index = (((rv.seq - 1) % 4) + 1)
JOIN tmp_dummy_restaurant rest
  ON rest.seq = (CASE WHEN MOD(rv.seq - 1, 10) < 6 THEN ((rv.seq - 1) % 1000) + 1 ELSE 1000 + (((rv.seq - 1) % 9000) + 1) END)
ORDER BY rv.seq;

WITH cfg AS (
  SELECT ARRAY['직원 응대가 친절하고 음식이 빨리 나왔습니다.', '대표 메뉴의 완성도가 높고 재료 신선도가 좋았습니다.', '매장 동선이 편하고 좌석 간격이 넉넉했습니다.']::TEXT[] AS positive_lines,
         ARRAY['피크타임에는 대기 시간이 길어질 수 있습니다.', '일부 메뉴는 간이 조금 강하게 느껴졌습니다.', '주차가 다소 불편한 편이었습니다.']::TEXT[] AS negative_lines,
         ARRAY['동료들과 점심 모임으로 방문했습니다.', '퇴근 후 소규모 모임으로 다녀왔습니다.', '주말 오후에 가족과 함께 이용했습니다.', '혼밥으로 방문했는데 부담이 적었습니다.']::TEXT[] AS context_lines
)
INSERT INTO review (id, member_id, restaurant_id, group_id, subgroup_id, is_recommended, content, created_at, updated_at)
SELECT
  rv.id,
  rv.member_id,
  rv.restaurant_id,
  rv.group_id,
  rv.subgroup_id,
  rv.is_recommended,
  CASE     WHEN MOD(rv.seq, 4) = 0 THEN '더미 리뷰 내용입니다.' || ' ' || cfg.context_lines[((rv.seq - 1) % CARDINALITY(cfg.context_lines)) + 1] || ' ' || cfg.positive_lines[((rv.seq - 1) % CARDINALITY(cfg.positive_lines)) + 1] || ' ' || cfg.negative_lines[((rv.seq - 1) % CARDINALITY(cfg.negative_lines)) + 1]     WHEN MOD(rv.seq, 4) = 1 THEN cfg.context_lines[((rv.seq - 1) % CARDINALITY(cfg.context_lines)) + 1] || ' ' || cfg.positive_lines[((rv.seq - 1) % CARDINALITY(cfg.positive_lines)) + 1]     WHEN MOD(rv.seq, 4) = 2 THEN '더미 리뷰 내용입니다.' || ' ' || cfg.negative_lines[((rv.seq - 1) % CARDINALITY(cfg.negative_lines)) + 1]     ELSE '더미 리뷰 내용입니다.' || ' 방문 ' || rv.seq || '회차 리뷰입니다.'   END,
  NOW() - ((rv.seq % 180) || ' days')::INTERVAL,
  NOW() - ((rv.seq % 180) || ' days')::INTERVAL
FROM tmp_dummy_review rv
CROSS JOIN cfg
ORDER BY rv.seq;

-- Review keywords (keyword 테이블이 비어있으면 skip)
DO $$
DECLARE
  keyword_count INTEGER;
  max_per_review INTEGER;
BEGIN
  SELECT COUNT(*) INTO keyword_count FROM tmp_dummy_keyword;
  IF keyword_count > 0 THEN
    max_per_review := LEAST(3, keyword_count);
    INSERT INTO review_keyword (review_id, keyword_id)
    SELECT
      rv.id,
      kw.id
    FROM tmp_dummy_review rv
    JOIN generate_series(0, max_per_review - 1) AS offs(off)
      ON offs.off < (1 + ((rv.seq - 1) % max_per_review))
    JOIN tmp_dummy_keyword kw
      ON kw.seq = ((((rv.seq - 1) % keyword_count) + offs.off) % keyword_count) + 1
    ON CONFLICT DO NOTHING;
  END IF;
END $$;

-- Restaurant review analysis
INSERT INTO restaurant_review_sentiment (restaurant_id, vector_epoch, model_version, positive_count, negative_count, neutral_count, positive_percent, negative_percent, neutral_percent, analyzed_at)
SELECT
  r.id,
  0,
  'dummy-v1',
  ((r.seq - 1) % 10) + 1,
  2,
  1,
  60,
  20,
  20,
  NOW()
FROM tmp_dummy_restaurant r
ON CONFLICT (restaurant_id) DO NOTHING;

INSERT INTO restaurant_review_summary (restaurant_id, vector_epoch, model_version, summary_json, analyzed_at)
SELECT
  r.id,
  0,
  'dummy-v1',
  '{"summary":"더미 리뷰 요약입니다.","highlights":["맛있다","친절하다"]}'::jsonb,
  NOW()
FROM tmp_dummy_restaurant r
ON CONFLICT DO NOTHING;

-- Notifications
WITH cfg AS (
  SELECT ARRAY['CHAT', 'SYSTEM', 'NOTICE']::TEXT[] AS notif_types,
         ARRAY['새 채팅이 도착했어요', '즐겨찾기한 식당에 새 리뷰가 올라왔어요', '관심 그룹 공지 확인해보세요', '지금 인기 많은 맛집을 확인해보세요']::TEXT[] AS title_pool,
         ARRAY['놓치지 않도록 지금 바로 확인해보세요.', '최근 반응이 좋아 빠르게 마감될 수 있어요.', '새로운 멤버의 추천 리뷰가 등록됐습니다.', '설정에서 알림 유형을 자유롭게 조정할 수 있어요.']::TEXT[] AS body_pool
)
INSERT INTO notification (member_id, notification_type, title, body, deep_link, event_id, created_at)
SELECT
  m.id,
  cfg.notif_types[(MOD(ns.seq, CARDINALITY(cfg.notif_types)) + 1)],
  '더미 알림 제목' || ' · ' || cfg.title_pool[((ns.seq) % CARDINALITY(cfg.title_pool)) + 1],
  '더미 알림 내용입니다.' || ' ' || cfg.body_pool[((ns.seq) % CARDINALITY(cfg.body_pool)) + 1] || ' (ref:' || (ns.seq + 1) || ')',
  CASE cfg.notif_types[(MOD(ns.seq, CARDINALITY(cfg.notif_types)) + 1)]     WHEN 'CHAT' THEN '/chat/rooms/' || ((ns.seq % 6000) + 1)     WHEN 'NOTICE' THEN '/groups/' || ((ns.seq % 1500) + 1)     ELSE '/notifications'   END,
  'dummy' || '-' || '546d8cf5709d' || '-' || ns.seq || '-' || SUBSTR(MD5('546d8cf5709d' || '-' || ns.seq::TEXT), 1, 8),
  NOW() - ((ns.seq % 90) || ' days')::INTERVAL
FROM generate_series(0, 399999) AS ns(seq)
JOIN tmp_dummy_member m
  ON m.seq = ((ns.seq % 10000) + 1)
CROSS JOIN cfg
ON CONFLICT (event_id) WHERE event_id IS NOT NULL DO NOTHING;

-- Member favorite restaurants
INSERT INTO member_favorite_restaurant (member_id, restaurant_id, created_at)
SELECT
  m.id,
  r.id,
  NOW() - ((fs.seq % 180) || ' days')::INTERVAL
FROM generate_series(0, 99999) AS fs(seq)
JOIN tmp_dummy_member m
  ON m.seq = ((fs.seq % 10000) + 1)
JOIN tmp_dummy_restaurant r
  ON r.seq = (((fs.seq / 10000) % 10000) + 1)
ON CONFLICT DO NOTHING;

-- Subgroup favorite restaurants
INSERT INTO subgroup_favorite_restaurant (member_id, subgroup_id, restaurant_id, created_at)
SELECT
  m.id,
  sg.id,
  r.id,
  NOW() - ((sfs.seq % 180) || ' days')::INTERVAL
FROM generate_series(0, 999) AS sfs(seq)
JOIN tmp_dummy_member m
  ON m.seq = ((sfs.seq % 10000) + 1)
JOIN tmp_dummy_subgroup sg
  ON sg.seq = (((sfs.seq / 10000) % 6000) + 1)
JOIN tmp_dummy_restaurant r
  ON r.seq = (((sfs.seq / 60000000) % 10000) + 1)
ON CONFLICT DO NOTHING;

-- Load-test bootstrap fixture for k6/locust scripts (phase1_test / locustfile)
CREATE TEMP TABLE tmp_loadtest_users (
  idx INTEGER PRIMARY KEY,
  identifier TEXT NOT NULL,
  nickname TEXT NOT NULL,
  member_id BIGINT
) ON COMMIT DROP;
INSERT INTO tmp_loadtest_users (idx, identifier, nickname)
SELECT
  gs,
  format('test-user-%s', lpad(gs::text, 3, '0')) AS identifier,
  format('부하테스트계정%s', gs) AS nickname
FROM generate_series(1, 1000) AS gs;

-- Load-test members + OAuth account
INSERT INTO member (id, email, nickname, status, role, profile_image_url, introduction, last_login_at, agreed_terms_at, agreed_privacy_at, created_at, updated_at)
SELECT
  nextval('member_seq'),
  tu.identifier || '@test.local',
  tu.nickname,
  'ACTIVE',
  'USER',
  NULL,
  NULL,
  NOW(),
  NOW() - INTERVAL '1 day',
  NOW() - INTERVAL '1 day',
  NOW(),
  NOW()
FROM tmp_loadtest_users tu
ON CONFLICT (email) DO NOTHING;

UPDATE tmp_loadtest_users tu
SET member_id = m.id
FROM member m
WHERE m.email = tu.identifier || '@test.local';

INSERT INTO member_oauth_account (id, member_id, provider, provider_user_id, provider_user_email, created_at)
SELECT
  nextval('member_oauth_account_seq'),
  tu.member_id,
  'TEST',
  tu.identifier,
  tu.identifier || '@test.local',
  NOW()
FROM tmp_loadtest_users tu
WHERE tu.member_id IS NOT NULL
ON CONFLICT ON CONSTRAINT uk_member_oauth_provider_user DO NOTHING;

INSERT INTO "group"
(id, name, type, logo_image_url, address, detail_address, location, join_type, email_domain, status, created_at, updated_at)
VALUES
(2002, '부하테스트 그룹', 'UNOFFICIAL', NULL, '서울시 강남구 테스트로', '역삼동 2002', ST_SetSRID(ST_MakePoint(127.0276, 37.4979), 4326), 'PASSWORD', NULL, 'ACTIVE', NOW(), NOW())
ON CONFLICT (id) DO UPDATE
SET
  name = EXCLUDED.name,
  type = EXCLUDED.type,
  logo_image_url = EXCLUDED.logo_image_url,
  address = EXCLUDED.address,
  detail_address = EXCLUDED.detail_address,
  location = EXCLUDED.location,
  join_type = EXCLUDED.join_type,
  email_domain = EXCLUDED.email_domain,
  status = EXCLUDED.status,
  updated_at = NOW();

INSERT INTO subgroup (id, group_id, name, description, profile_image_url, join_type, join_password, status, member_count, created_at, updated_at)
VALUES
(4002, 2002, '부하테스트 서브그룹', '부하테스트용 서브그룹입니다.', NULL, 'OPEN', NULL, 'ACTIVE', 0, NOW(), NOW())
ON CONFLICT (id) DO UPDATE
SET
  group_id = EXCLUDED.group_id,
  name = EXCLUDED.name,
  description = EXCLUDED.description,
  profile_image_url = EXCLUDED.profile_image_url,
  join_type = EXCLUDED.join_type,
  join_password = EXCLUDED.join_password,
  status = EXCLUDED.status,
  updated_at = NOW();

INSERT INTO chat_room (subgroup_id, created_at)
SELECT 4002, NOW()
WHERE NOT EXISTS (SELECT 1 FROM chat_room WHERE subgroup_id = 4002);

CREATE TEMP TABLE tmp_loadtest_chat_room AS
SELECT id AS chat_room_id FROM chat_room WHERE subgroup_id = 4002 ORDER BY id LIMIT 1;

INSERT INTO group_member (id, group_id, member_id, created_at)
SELECT nextval('group_member_seq'), 2002, tu.member_id, NOW()
FROM tmp_loadtest_users tu
WHERE tu.member_id IS NOT NULL
ON CONFLICT ON CONSTRAINT uk_group_member_group_id_member_id DO NOTHING;

INSERT INTO subgroup_member (id, subgroup_id, member_id, created_at)
SELECT nextval('subgroup_member_seq'), 4002, tu.member_id, NOW()
FROM tmp_loadtest_users tu
WHERE tu.member_id IS NOT NULL
ON CONFLICT ON CONSTRAINT uk_subgroup_member_subgroup_id_member_id DO NOTHING;

INSERT INTO chat_room_member (member_id, chat_room_id, created_at, updated_at)
SELECT
  tu.member_id,
  cr.chat_room_id,
  NOW(),
  NOW()
FROM tmp_loadtest_users tu
CROSS JOIN tmp_loadtest_chat_room cr
WHERE tu.member_id IS NOT NULL
ON CONFLICT (chat_room_id, member_id) DO NOTHING;

UPDATE subgroup
SET member_count = (SELECT COUNT(*) FROM subgroup_member WHERE subgroup_id = 4002 AND deleted_at IS NULL)
WHERE id = 4002;

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_extension WHERE extname = 'pgcrypto') THEN
    RAISE WARNING 'pgcrypto extension not found: group_auth_code for load-test group skipped';
    RETURN;
  END IF;

  DELETE FROM group_auth_code WHERE group_id = 2002;
  INSERT INTO group_auth_code (id, group_id, code, created_at) VALUES (nextval('group_auth_code_seq'), 2002, crypt('LOCAL-1234', gen_salt('bf', 12)), NOW());
END $$;

COMMIT;
