name: Backend CI/CD - Full Pipeline

on:
  push:
    branches:
      - develop
      - main
  pull_request:
    branches:
      - develop
      - main

jobs:
  # PR 시에만 보안 검사 실행
  security-scan:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    timeout-minutes: 20
    permissions:
      contents: read
      security-events: write

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'gradle'

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      # CodeQL 보안 분석 - 빌드 전에 초기화
      - name: Initialize CodeQL
        uses: github/codeql-action/init@v4
        with:
          languages: java
          queries: security-and-quality

      # 테스트 + 컴파일만 실행 (JAR 생성 안함, SpotBugs 제외)
      - name: Run Tests and Compile
        run: ./gradlew test

      # CodeQL 분석 수행
      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v4
        with:
          category: "/language:java"

      # 보안 분석 - SpotBugs (한 번만 명시적 실행)
      - name: Run SpotBugs Security Analysis
        run: ./gradlew :app-api:spotbugsMain
        continue-on-error: true

      # SpotBugs 리포트 업로드
      - name: Upload SpotBugs Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: spotbugs-report-${{ github.sha }}
          path: app-api/build/reports/spotbugs/main/spotbugs.html
          retention-days: 7

      # 보안 스캔 실패 알림 (성공 시 알림 없음)
      - name: Notify Security Scan Failure
        if: failure()
        uses: sarisia/actions-status-discord@v1
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK_URL }}
          title: "백엔드 보안 스캔 실패 ❌"
          description: |
            **결과:** 실패
            **브랜치:** ${{ github.ref_name }}
            **작성자:** ${{ github.actor }}
            **커밋:** ${{ github.sha }}
            **이벤트:** PR 보안 검사
          color: 0xff0000

  # develop push 시에만 빌드 & 배포
  build-and-deploy:
    if: github.event_name == 'push' && github.ref == 'refs/heads/develop'
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'gradle'

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      # 배포용 빌드 (JAR 생성, 테스트는 PR에서 이미 완료)
      - name: Build JAR for deployment
        run: ./gradlew build -x test

      # JAR 파일 업로드 (deploy job에서 사용, plain JAR 제외)
      - name: Upload JAR artifact
        uses: actions/upload-artifact@v4
        with:
          name: backend-jar-${{ github.sha }}
          path: app-api/build/libs/*[!plain].jar
          retention-days: 1

      # 빌드 실패 알림
      - name: Notify Build Failure
        if: failure()
        uses: sarisia/actions-status-discord@v1
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK_URL }}
          title: "백엔드 빌드 실패 ❌"
          description: |
            **결과:** 실패
            **브랜치:** ${{ github.ref_name }}
            **작성자:** ${{ github.actor }}
            **커밋:** ${{ github.sha }}
            **이벤트:** develop 브랜치 빌드
          color: 0xff0000

  deploy:
    needs: build-and-deploy
    if: github.event_name == 'push' && github.ref == 'refs/heads/develop'
    runs-on: ubuntu-latest

    steps:
      # 빌드 산출물 다운로드
      - name: Download Build Artifact
        uses: actions/download-artifact@v4
        with:
          name: backend-jar-${{ github.sha }}
          path: ./deploy-temp

      # 개발 서버로 JAR 전송
      - name: Transfer JAR to Development Server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.DEVELOP_HOST }}
          username: ${{ secrets.DEVELOP_USERNAME }}
          key: ${{ secrets.DEVELOP_KEY }}
          port: ${{ secrets.DEVELOP_PORT || 22 }}
          source: "./deploy-temp/*.jar"
          target: "/home/${{ secrets.DEVELOP_USERNAME }}/backend/temp"
          strip_components: 1

      # 무중단 배포 스크립트 실행
      - name: Execute Blue-Green Deployment
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DEVELOP_HOST }}
          username: ${{ secrets.DEVELOP_USERNAME }}
          key: ${{ secrets.DEVELOP_KEY }}
          port: ${{ secrets.DEVELOP_PORT || 22 }}
          script: |
            # JAR 파일명 추출 및 경로 설정
            JAR_NAME=$(ls -t /home/${{ secrets.DEVELOP_USERNAME }}/backend/temp/*.jar | head -1)
            DEPLOY_SCRIPT="/home/${{ secrets.DEVELOP_USERNAME }}/deploy/deploy.sh"

            # 스크립트 실행 권한 부여
            chmod +x $DEPLOY_SCRIPT

            # 무중단 배포 스크립트 호출
            $DEPLOY_SCRIPT $JAR_NAME

      # 배포 결과 알림
      - name: Notify Deployment Result
        if: always()
        uses: sarisia/actions-status-discord@v1
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK_URL }}
          title: "백엔드 개발 서버 배포 ${{ job.status == 'success' && '성공 ✅' || '실패 ❌' }}"
          description: |
            **결과:** ${{ job.status }}
            **브랜치:** ${{ github.ref_name }}
            **작성자:** ${{ github.actor }}
            **커밋:** ${{ github.sha }}
            **서버 환경:** 개발 서버
          color: ${{ job.status == 'success' && '0x00ff00' || '0xff0000' }}
