name: Backend Feature CI - Quick Check

on:
  push:
    branches:
      - feat/**
      - hotfix/**

jobs:
  quick-check:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      # 1주차 생략
      # formatting
      #      - name: Run Spotless Check
      #        run: ./gradlew spotlessCheck

      # 1주차 생략
      # convention
      #      - name: Run Checkstyle
      #        run: ./gradlew checkstyleMain checkstyleTest

      # 빌드
      - name: Build with Gradle
        run: ./gradlew build -x test

      # Feature 브랜치에서는 테스트와 SonarCloud 생략

      # CI 결과 알림 (실패 시에만)
      - name: Notify CI result to Discord
        if: failure()
        uses: sarisia/actions-status-discord@v1
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK_URL }}
          title: "백엔드 Feature CI 실패 ❌"
          description: |
            **결과:** ${{ job.status }}
            **브랜치:** ${{ github.ref_name }}
            **작성자:** ${{ github.actor }}
            **커밋:** ${{ github.sha }}
          color: 0xff0000