name: AI PR CI - Full Check

on:
  pull_request:
    branches:
      - develop
      - main

jobs:
  full-check:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # 문법 체크
      - name: Syntax Check
        run: python -m py_compile app.py

      # Import 검증
      - name: Verify Imports
        run: |
          python -c "from src.api.main import app; print('FastAPI app imported successfully')"

      # 테스트코드
      - name: Run Tests
        run: python test_all_task.py

      # CI 결과 알림 (PR은 항상)
      - name: Notify CI result to Discord
        if: failure()
        uses: sarisia/actions-status-discord@v1
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK_URL }}
          title: "AI PR CI ${{ '실패 ❌' }}"
          description: |
            **결과:** ${{ job.status }}
            **브랜치:** ${{ github.ref_name }}
            **작성자:** ${{ github.actor }}
            **커밋:** ${{ github.sha }}
          color: ${{ job.status == 'success' && '0x00ff00' || '0xff0000' }}
