name: AI Feature CI - Quick Check

on:
  push:
    branches:
      - feat/**
      - hotfix/**

jobs:
  quick-check:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      # 문법 체크 (의존성 설치 불필요)
      - name: Syntax Check
        run: python -m py_compile app.py

      # CI 결과 알림 (실패 시에만)
      - name: Notify CI result to Discord
        if: failure()
        uses: sarisia/actions-status-discord@v1
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK_URL }}
          title: "AI Feature CI 실패 ❌"
          description: |
            **결과:** ${{ job.status }}
            **브랜치:** ${{ github.ref_name }}
            **작성자:** ${{ github.actor }}
            **커밋:** ${{ github.sha }}
          color: 0xff0000
